### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by jasta** [jasta/esp32-balboa-spa#1]
Issues blocking first deployment in the "real world" environment

- [ ] 3D printed case
- [ ] Adhesive backed laminated cover
- [ ] Waterproof test
- [ ] Ability to toggle jet/light status
- [ ] UI presentation for jet/light status
- [ ] UI presentation for Wi-Fi status
- [ ] UI presentation for set temp vs current temp
- [ ] OTA server
- [ ] Signed firmware checking/validation enabled
- [ ] Repair wiring to panel location
- [ ] Functional test before final adhesive application

**Comment by TheBestJohn** [comment]
This is super cool. I just learned about the whole balboa serial port stuff and am putting together an adapter now. I know a bit of rust, not embedded rust though. I know for sure I could contribute a printed case model.
